[versions]
# libraries
jacksonModuleKotlin = "2.17.2"

# plugins
kotlin = "2.0.0"
changelog = "2.2.1"
gradleIntelliJPlugin = "1.17.4"
qodana = "0.1.13"
kover = "0.8.3"

[libraries]
jacksonModuleKotlin = { group = "com.fasterxml.jackson.module", name = "jackson-module-kotlin", version.ref = "jacksonModuleKotlin" }

[plugins]
changelog = { id = "org.jetbrains.changelog", version.ref = "changelog" }
gradleIntelliJPlugin = { id = "org.jetbrains.intellij", version.ref = "gradleIntelliJPlugin" }
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kover = { id = "org.jetbrains.kotlinx.kover", version.ref = "kover" }
qodana = { id = "org.jetbrains.qodana", version.ref = "qodana" }
